# Generated by Django 2.0 on 2020-06-10 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.FileField(blank=True, upload_to='avatar/%Y%m%d/'),
        ),
    ]
