# Generated by Django 2.0 on 2020-06-10 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_auto_20200403_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='root',
        ),
    ]
